import { fastifyRequestContext } from "@fastify/request-context";
import type { FastifyInstance } from "fastify";

declare module "@fastify/request-context" {
  // Augmented per @fastify/request-context typings.
  interface RequestContextData {
    requestId: string;
    userId?: string;
    role?: string;
  }
}

// Populates the async-local store with the request ID generated by Fastify's
// genReqId (configured in app.ts to honor X-Request-Id or generate a UUID).
// Downstream code can read it without threading the ID through every call.
export async function registerRequestContext(app: FastifyInstance): Promise<void> {
  await app.register(fastifyRequestContext, {
    defaultStoreValues: { requestId: "" },
  });

  app.addHook("onRequest", (req, _reply, done) => {
    req.requestContext.set("requestId", req.id);
    done();
  });
}
