image: node:20-alpine

definitions:
  steps:
    - step: &deploy
        name: Deploy to EC2
        runs-on:
          - self.hosted
          - linux.shell
        script:
          - sh /home/ubuntu/zadpay/scripts/deploy.sh

pipelines:
  branches:
    main:
      - step: *deploy #test32