// Payment requests — the spine of receive, qr, checkout, pos, nfc-pos.
//
// A payment request is a userdata row (feature='payment_requests') created
// by the *recipient* with the amount, currency, and an optional note. The
// recipient encodes the request payload as a QR code (or shares it as a
// URL). The *payer* scans/opens it and pays via the existing send-by-phone
// flow. After the transfer posts, the payer's client also flips the
// request's `status` to `"paid"` so the recipient sees it cleared.
//
// Wire payload (encoded in QR / deep link):
//   {
//     v: 1,
//     type: "zadpay.pay",
//     phone: "+15551234567",     // recipient phone (E.164)
//     amount: 7000,              // minor units (cents)
//     currency: "USD",
//     note?: "Coffee",
//     requestId?: "uuid"         // points back to the userdata row
//   }

import { useMutation, useQueryClient } from "@tanstack/react-query";
import { type ClientError } from "@/lib/api/errors";
import { useUserItems } from "./hooks";
import { userdataService } from "./service";

const FEATURE = "payment_requests";

export type PaymentRequestStatus = "pending" | "paid" | "cancelled";

export interface PaymentRequestPayload {
  /** Recipient's phone in E.164. Stored so the payer can resolve it without an extra lookup. */
  recipientPhone: string;
  /** Recipient's display name at request time. */
  recipientName: string;
  /** Amount in minor units (e.g. cents). Stored as a string because JSON drops bigint precision. */
  amountMinor: string;
  currency: string;
  note?: string;
  status: PaymentRequestStatus;
  /** Free-form context — e.g. "qr", "receive", "checkout:<orderId>", "pos:<terminalId>". */
  channel: string;
  /** Set when status flips to "paid". */
  paidAt?: string;
  /** Wallet transaction id once paid — lets the recipient deep-link to the receipt. */
  paidTransactionId?: string;
}

export interface WireQrPayload {
  v: 1;
  type: "zadpay.pay";
  phone: string;
  amount: number; // minor units
  currency: string;
  note?: string;
  requestId?: string;
}

export function buildWirePayload(args: {
  phone: string;
  amountMinor: number;
  currency: string;
  note?: string;
  requestId?: string;
}): WireQrPayload {
  return {
    v: 1,
    type: "zadpay.pay",
    phone: args.phone,
    amount: args.amountMinor,
    currency: args.currency,
    ...(args.note !== undefined && args.note.length > 0 ? { note: args.note } : {}),
    ...(args.requestId !== undefined ? { requestId: args.requestId } : {}),
  };
}

/// Validates an arbitrary scanned string and returns the parsed wire
/// payload if it conforms, or null if it doesn't. Used by the QR scanner.
export function parseWirePayload(raw: string): WireQrPayload | null {
  try {
    const obj = JSON.parse(raw) as unknown;
    if (obj === null || typeof obj !== "object") return null;
    const r = obj as Record<string, unknown>;
    if (r.v !== 1) return null;
    if (r.type !== "zadpay.pay") return null;
    if (typeof r.phone !== "string" || r.phone.length === 0) return null;
    if (typeof r.amount !== "number" || r.amount < 0 || !Number.isFinite(r.amount)) return null;
    if (typeof r.currency !== "string" || r.currency.length === 0) return null;
    const out: WireQrPayload = {
      v: 1,
      type: "zadpay.pay",
      phone: r.phone,
      amount: Math.round(r.amount),
      currency: r.currency,
    };
    if (typeof r.note === "string" && r.note.length > 0) out.note = r.note;
    if (typeof r.requestId === "string" && r.requestId.length > 0) out.requestId = r.requestId;
    return out;
  } catch {
    return null;
  }
}

export function usePaymentRequests() {
  return useUserItems<PaymentRequestPayload>(FEATURE);
}

export function useCreatePaymentRequest() {
  const qc = useQueryClient();
  return useMutation<
    { id: string; payload: PaymentRequestPayload },
    ClientError,
    Omit<PaymentRequestPayload, "status">
  >({
    mutationFn: async (input) => {
      const payload: PaymentRequestPayload = { ...input, status: "pending" };
      const r = await userdataService.create(
        FEATURE,
        payload as unknown as Record<string, unknown>,
      );
      if (!r.ok) throw r.error;
      return { id: r.value.id, payload };
    },
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: ["userdata", FEATURE] });
    },
  });
}

/// Marks a payment request as paid. Tolerates 404 — the payer might be
/// scanning a QR whose request was generated by a different account, or
/// the recipient may have cleared their device storage.
export async function markPaymentRequestPaid(
  requestId: string,
  paidTransactionId: string,
): Promise<void> {
  const existing = await userdataService.list(FEATURE);
  if (!existing.ok) return;
  const row = existing.value.items.find((it) => it.id === requestId);
  if (row === undefined) return;
  const next: PaymentRequestPayload = {
    ...(row.payload as unknown as PaymentRequestPayload),
    status: "paid",
    paidAt: new Date().toISOString(),
    paidTransactionId,
  };
  await userdataService.update(FEATURE, requestId, next as unknown as Record<string, unknown>);
}

export async function cancelPaymentRequest(requestId: string): Promise<void> {
  const existing = await userdataService.list(FEATURE);
  if (!existing.ok) return;
  const row = existing.value.items.find((it) => it.id === requestId);
  if (row === undefined) return;
  const next: PaymentRequestPayload = {
    ...(row.payload as unknown as PaymentRequestPayload),
    status: "cancelled",
  };
  await userdataService.update(FEATURE, requestId, next as unknown as Record<string, unknown>);
}
